# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Giu Node.js CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
#        cache: 'npm'

    - name: npm install, make test-coverage
      run: |
        npm i
        make test-coverage
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
#    - run: npm run build --if-present
#    - run: npm run test:cov
